import React from 'react';
import Head from "next/head";
import Link from "next/link";

const Layout = ({ children, title }) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className="bg-slate-900 py-6 md:py-10 mb-6 md:mb-10">
                <div className="container mx-auto px-4">
                    <Link href="/">
                        <a>
                            <h1 className="text-4xl md:text-6xl text-center text-amber-400">{title}</h1>
                        </a>
                    </Link>
                </div>
            </header>

            <main className="container mx-auto px-4">
                {children}
            </main>
        </div>
    );
};

export default Layout;
